# Generated by Django 6.0.2 on 2026-02-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachbooking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('supplements', 'Supplements'), ('activewear_male', 'Active Wear (Male)'), ('activewear_female', 'Active Wear (Female)'), ('equipment', 'Gym Equipment'), ('meal_plan', 'Meal Plans')], default='activewear_male', max_length=20),
        ),
    ]
